### ISSUE TITLE
How to know if this bundle is called automatically?

### ISSUE THREAD

**Issue by alexislefebvre** [sensiolabs/minify-bundle#16]
I have installed this bundle and it uses `download_binary: true` in `config/packages/sensiolabs_minify.yaml`.

I can download the binary:

```bash
/app # bin/console minify:install

 [OK] The Minify binary has been installed
```

Then I run `asset-map:compile` to simulate a deployment:

```
/app # bin/console --env=prod asset-map:compile -vvv

 // Compiling and writing asset files to public

 // Compiled 301 assets

 // Manifest written to public/assets/manifest.json

 // Import map data written to public/assets/importmap.json.

 // Entrypoint metadata written for 1 entrypoints (app).
```

**How to know if this bundle is called automatically?** Is a text supposed to appear to confirm that some files were minified when running `asset-map:compile`?

Then I set `download_binary: true`, delete the binary and run `asset-map:compile` to simulate a deployment:

```
/app # rm -v var/minify/minify 
removed 'var/minify/minify'
/app # bin/console --env=prod asset-map:compile -vvv

 // Compiling and writing asset files to public                                                                         

 // Compiled 301 assets                                                                                                 

 // Manifest written to public/assets/manifest.json                                                                     

 // Import map data written to public/assets/importmap.json.                                                            

 // Entrypoint metadata written for 1 entrypoints (app).      
```

It should fail since I deleted the binary, but there is no error message.

So it looks like something is missing to call `minify-bundle`, it neither minify files or crash when the binary is missing.

**Comment by smnandre** [comment]
> I tried on another project and it looks like it works once we delete the cache.

Yes, assetmapper requires a `php bin/console c:p:c --all` i think
